
export const REQUEST_POLLS_START = 'REQUEST_POLLS_START';
export const REQUEST_POLLS_SUCCESS = 'REQUEST_POLLS_SUCCESS';
export const REQUEST_POLLS_FAILED = 'REQUEST_POLLS_FAILED';

export const MAKE_POLL_START = "MAKE_POLL_START";
export const MAKE_POLL_SUCCESS = 'MAKE_POLL_SUCCESS';
export const MAKE_POLL_FAILED = 'MAKE_POLL_FAILED';

export const pollConstants = {
    POLL_REGISTER_REQUEST: 'POLL_REGISTER_REQUEST',
    POLL_REGISTER_SUCCESS: 'POLL_REGISTER_SUCCESS',
    POLL_REGISTER_FAILURE: 'POLL_REGISTER_FAILURE',

    POLL_VOTE_REQUEST: 'POLL_VOTE_REQUEST',
    POLL_VOTE_SUCCESS: 'POLL_VOTE_SUCCESS',
    POLL_VOTE_FAILURE: 'POLL_VOTE_FAILURE',

    POLL_USER_VOTE_REQUEST: 'POLL_USER_VOTE_REQUEST',
    POLL_USER_VOTE_SUCCESS: 'POLL_USER_VOTE_SUCCESS',
    POLL_USER_VOTE_FAILURE: 'POLL_USER_VOTE_FAILURE',


    POLL_VOTE_MULTIPLE_REQUEST: 'POLL_VOTE_MULTIPLE_REQUEST',
    POLL_VOTE_MULTIPLE_SUCCESS: 'POLL_VOTE_MULTIPLE_SUCCESS',
    POLL_VOTE_MULTIPLE_FAILURE: 'POLL_VOTE_MULTIPLE_FAILURE',


    GETALL_REQUEST: 'POLLS_GETALL_REQUEST',
    GETALL_SUCCESS: 'POLLS_GETALL_SUCCESS',
    GETALL_FAILURE: 'POLLS_GETALL_FAILURE',

    
    GETONE_REQUEST: 'POLLS_GETONE_REQUEST',
    GETONE_SUCCESS: 'POLLS_GETONE_SUCCESS',
    GETONE_FAILURE: 'POLLS_GETONE_FAILURE',
    GETONE_SELECT: "GETONE_SELECT"

/*
    LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
    LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
    LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

    LOGOUT: 'USERS_LOGOUT',

   

    DELETE_REQUEST: 'USERS_DELETE_REQUEST',
    DELETE_SUCCESS: 'USERS_DELETE_SUCCESS',
    DELETE_FAILURE: 'USERS_DELETE_FAILURE'   
*/ 
};