export const pollConstants = {
    POLL_REGISTER_REQUEST: 'POLL_REGISTER_REQUEST',
    POLL_REGISTER_SUCCESS: 'POLL_REGISTER_SUCCESS',
    POLL_REGISTER_FAILURE: 'POLL_REGISTER_FAILURE',

    POLL_VOTE_ANSWER_REQUEST: 'POLL_VOTE_ANSWER_REQUEST',
    POLL_VOTE_ANSWER_SUCCESS: 'POLL_VOTE_ANSWER_SUCCESS',
    POLL_VOTE_ANSWER_FAILURE: 'POLL_VOTE_ANSWER_FAILURE',

    POLL_VOTE_USERANSWER_REQUEST: 'POLL_VOTE_USERANSWER_REQUEST',
    POLL_VOTE_USERANSWER_SUCCESS: 'POLL_VOTE_USERANSWER_SUCCESS',
    POLL_VOTE_USERANSWER_FAILURE: 'POLL_VOTE_USERANSWER_FAILURE',

    POLL_VOTE_CREATEUSERANSWER_REQUEST: 'POLL_VOTE_CREATEUSERANSWER_REQUEST',
    POLL_VOTE_CREATEUSERANSWER_SUCCESS: 'POLL_VOTE_CREATEUSERANSWER_SUCCESS',
    POLL_VOTE_CREATEUSERANSWER_FAILURE: 'POLL_VOTE_CREATEUSERANSWER_FAILURE',

    CHECK_POLL_REQUEST: 'CHECK_POLL_REQUEST',
    CHECK_POLL_SUCCESS: 'CHECK_POLL_SUCCESS',
    CHECK_POLL_FAILURE: 'CHECK_POLL_FAILURE',

    DELETE_POLL_REQUEST: 'DELETE_POLL_REQUEST',
    DELETE_POLL_SUCCESS: 'DELETE_POLL_SUCCESS',
    DELETE_POLL_FAILURE: 'DELETE_POLL_FAILURE',

    EDIT_POLL_REQUEST: 'EDIT_POLL_REQUEST',
    EDIT_POLL_SUCCESS: 'EDIT_POLL_SUCCESS',
    EDIT_POLL_FAILURE: 'EDIT_POLL_FAILURE',

    POLL_USER_VOTE_REQUEST: 'POLL_USER_VOTE_REQUEST',
    POLL_USER_VOTE_SUCCESS: 'POLL_USER_VOTE_SUCCESS',
    POLL_USER_VOTE_FAILURE: 'POLL_USER_VOTE_FAILURE',

    POLL_VOTE_MULTIPLE_REQUEST: 'POLL_VOTE_MULTIPLE_REQUEST',
    POLL_VOTE_MULTIPLE_SUCCESS: 'POLL_VOTE_MULTIPLE_SUCCESS',
    POLL_VOTE_MULTIPLE_FAILURE: 'POLL_VOTE_MULTIPLE_FAILURE',

    GET_REQUEST: 'POLLS_GET_REQUEST',
    GET_SUCCESS: 'POLLS_GET_SUCCESS',
    GET_FAILURE: 'POLLS_GET_FAILURE',
    GET_SELECT: "GET_SELECT",

    POLL_RESCIND_REQUEST: "POLL_RESCIND_REQUEST", 
    POLL_RESCIND_SUCCESS: "POLL_RESCIND_SUCCESS", 
    POLL_RESCIND_FAILURE: "POLL_RESCIND_FAILURE"
};