export const pollConstants = {
    POLL_REGISTER_REQUEST: 'POLL_REGISTER_REQUEST',
    POLL_REGISTER_SUCCESS: 'POLL_REGISTER_SUCCESS',
    POLL_REGISTER_FAILURE: 'POLL_REGISTER_FAILURE',

    POLL_VOTE_REQUEST: 'POLL_VOTE_REQUEST',
    POLL_VOTE_SUCCESS: 'POLL_VOTE_SUCCESS',
    POLL_VOTE_FAILURE: 'POLL_VOTE_FAILURE',

    POLL_USER_VOTE_REQUEST: 'POLL_USER_VOTE_REQUEST',
    POLL_USER_VOTE_SUCCESS: 'POLL_USER_VOTE_SUCCESS',
    POLL_USER_VOTE_FAILURE: 'POLL_USER_VOTE_FAILURE',


    POLL_VOTE_MULTIPLE_REQUEST: 'POLL_VOTE_MULTIPLE_REQUEST',
    POLL_VOTE_MULTIPLE_SUCCESS: 'POLL_VOTE_MULTIPLE_SUCCESS',
    POLL_VOTE_MULTIPLE_FAILURE: 'POLL_VOTE_MULTIPLE_FAILURE',

    GETONE_REQUEST: 'POLLS_GETONE_REQUEST',
    GETONE_SUCCESS: 'POLLS_GETONE_SUCCESS',
    GETONE_FAILURE: 'POLLS_GETONE_FAILURE',
    GETONE_SELECT: "GETONE_SELECT"
};