
export const REQUEST_POLLS_START = 'REQUEST_POLLS_START';
export const REQUEST_POLLS_SUCCESS = 'REQUEST_POLLS_SUCCESS';
export const REQUEST_POLLS_FAILED = 'REQUEST_POLLS_FAILED';


export const MAKE_POLL_START = "MAKE_POLL_START";
export const MAKE_POLL_SUCCESS = 'MAKE_POLL_SUCCESS';
export const MAKE_POLL_FAILED = 'MAKE_POLL_FAILED';
